# basic options, this is coment section
title: Golam Mostapha Khan 
author: Golam M Khan 
email: mustapha786@gmail.com
description: Golam Mostapha Khan Resume 
twitter_username: mustapha786 
github_username:  mustapha786
linkedIn_username: mustapha786

# Build settings
markdown: kramdown
theme: jekyll-theme-slate
