# basic options, this is coment section
title: Golam Mostapha Khan 
author: Golam M Khan 
email: mustapha786@gmail.com
description: “All things are created twice; first mentally; then physically.  The key to creativity is to begin with the end in mind, with a vision and a blue print of the desired result.”
               — Stephen Covey
twitter_username: mustapha786 
github_username:  mustapha786
linkedIn_username: mustapha786

# Build settings
markdown: kramdown
theme: jekyll-theme-resume
